MRS=pypy ../mrs_gp.py

clean: 
	rm -rf /tmp/test-copy

# file-file

copy:
	bash start-server.sh
	$(MRS) --task --input test --output /tmp/test-copy --mapper cat
	$(MRS) --shutdown
	echo should be the same
	sum test/* /tmp/test-copy/*

copy2:
	bash start-server.sh
	$(MRS) --task --input test --output /tmp/test-copy --mapper cat
	$(MRS) --task --input test --output /tmp/test-copy --mapper cat
	$(MRS) --shutdown
	echo should be the same
	sum test/* /tmp/test-copy/*

shard:
	bash start-server.sh
	$(MRS) --task --input test --output /tmp/test-copy --mapper cat --reducer cat --numReduceTasks 3
	$(MRS) --shutdown
	echo should have 3 files
	ls /tmp/test-copy
	echo should be the same
	sort test/* | sum
	sort /tmp/test-copy/* | sum

reshard:
	make -f Makefile.serve shard
	bash start-server.sh
	$(MRS) --task --input /tmp/test-copy --output /tmp/test-copy2 --mapper cat --reducer cat --numReduceTasks 2
	$(MRS) --shutdown
	echo should have 3 files
	ls /tmp/test-copy
	echo should have 2 files
	ls /tmp/test-copy2
	echo should be the same
	sort test/* | sum
	sort /tmp/test-copy/* | sum
	sort /tmp/test-copy2/* | sum

# file-memory 

load:
	bash start-server.sh
	$(MRS) --task --input test --output gpfs:test-copy --mapper cat
	$(MRS) --send 'cat?dir=test-copy&file=small.txt' | tail -n +2 > tmp.txt
	$(MRS) --shutdown
	echo should be the same
	sum test/* tmp.txt

load-shard:
	bash start-server.sh
	$(MRS) --task --input test --output gpfs:test-copy --mapper cat --reducer cat --numReduceTasks 3
	echo should have 3 files
	$(MRS) --send 'ls?dir=test-copy'
	$(MRS) --send 'getmerge?dir=test-copy' | tail -n +2 > tmp.txt
	$(MRS) --shutdown
	echo should be the same
	sort test/* | sum
	sort tmp.txt | sum

roundtrip:
	bash start-server.sh
	$(MRS) --task --input test --output gpfs:test-copy --mapper cat 
	$(MRS) --task --output /tmp/test-copy --input gpfs:test-copy --mapper cat
	$(MRS) --shutdown
	echo should be the same
	sort test/* | sum
	sort /tmp/test-copy/* | sum

roundtrip-reshard:
	bash start-server.sh
	$(MRS) --task --input test --output gpfs:test-copy --mapper cat --reducer cat --numReduceTasks 3
	$(MRS) --task --output /tmp/test-copy --input gpfs:test-copy --mapper cat --reducer cat --numReduceTasks 2
	$(MRS) --shutdown
	echo should be the same
	sort test/* | sum
	sort /tmp/test-copy/* | sum

